
import { Service, Translations } from './types.ts';
import { WebIcon, ServerIcon, DataScienceIcon, ScrapingIcon, PipelinesIcon, IntegrationIcon, Web3Icon } from './components/ui/Icons.tsx';

export const SERVICES: Service[] = [
  { id: 'web', titleKey: 'service_web_title', descriptionKey: 'service_web_desc', icon: WebIcon },
  { id: 'server', titleKey: 'service_server_title', descriptionKey: 'service_server_desc', icon: ServerIcon },
  { id: 'datascience', titleKey: 'service_ds_title', descriptionKey: 'service_ds_desc', icon: DataScienceIcon },
  { id: 'scraping', titleKey: 'service_scraping_title', descriptionKey: 'service_scraping_desc', icon: ScrapingIcon },
  { id: 'pipelines', titleKey: 'service_pipelines_title', descriptionKey: 'service_pipelines_desc', icon: PipelinesIcon },
  { id: 'integration', titleKey: 'service_integration_title', descriptionKey: 'service_integration_desc', icon: IntegrationIcon },
  { id: 'web3', titleKey: 'service_web3_title', descriptionKey: 'service_web3_desc', icon: Web3Icon },
];

export const I18N_STRINGS: Translations = {
  // General
  logo_alt: { en: 'u-cloud24 Logo', ru: 'Логотип u-cloud24', pl: 'Logo u-cloud24' },
  register_cta: { en: 'Start Registration', ru: 'Начать регистрацию', pl: 'Rozpocznij rejestrację' },
  all_rights_reserved: { en: 'All rights reserved.', ru: 'Все права защищены.', pl: 'Wszelkie prawa zastrzeżone.' },
  home: { en: 'Home', ru: 'Главная', pl: 'Strona główna' },
  services: { en: 'Services', ru: 'Услуги', pl: 'Usługi' },
  
  // Hero Section
  hero_title: { en: 'Unified Cloud Ecosystem', ru: 'Единая облачная экосистема', pl: 'Zunifikowany Ekosystem Chmurowy' },
  hero_subtitle: { en: 'From scalable servers to powerful solutions, build your future with a platform designed for innovation and performance.', ru: 'От масштабируемых серверов до мощных решений — стройте свое будущее на платформе, созданной для инноваций и производительности.', pl: 'Od skalowalnych serwerów po potężne rozwiązania, buduj swoją przyszłość z platformą zaprojektowaną dla innowacji i wydajności.' },
  
  // Services Grid
  bento_title: { en: 'Our Services', ru: 'Наши Услуги', pl: 'Nasze Usługi' },
  bento_subtitle: { en: 'A comprehensive suite of tools to power your projects.', ru: 'Полный набор инструментов для ваших проектов.', pl: 'Kompleksowy zestaw narzędzi do zasilania Twoich projektów.' },
  
  // Service Titles & Descriptions (for cards)
  service_web_title: { en: 'Web Apps', ru: 'Веб-приложения', pl: 'Aplikacje Webowe' },
  service_web_desc: { en: 'Modern, fast, and scalable web applications.', ru: 'Современные, быстрые и масштабируемые веб-приложения.', pl: 'Nowoczesne, szybkie i skalowalne aplikacje webowe.' },
  service_server_title: { en: 'Cloud Servers', ru: 'Облачные серверы', pl: 'Serwery Chmurowe' },
  service_server_desc: { en: 'Reliable and powerful virtual server infrastructure.', ru: 'Надежная и мощная инфраструктура виртуальных серверов.', pl: 'Niezawodna i wydajna infrastruktura serwerów wirtualnych.' },
  service_ds_title: { en: 'Data Science', ru: 'Data Science', pl: 'Data Science' },
  service_ds_desc: { en: 'Unlock insights from your data with advanced analytics.', ru: 'Извлекайте ценные сведения из данных с помощью передовой аналитики.', pl: 'Odkryj spostrzeżenia z Twoich danych dzięki zaawansowanej analityce.' },
  service_scraping_title: { en: 'Web Scraping', ru: 'Веб-скрапинг', pl: 'Web Scraping' },
  service_scraping_desc: { en: 'Efficient and ethical data extraction from the web.', ru: 'Эффективное и этичное извлечение данных из веба.', pl: 'Efektywne i etyczne pozyskiwanie danych z sieci.' },
  service_pipelines_title: { en: 'Data Pipelines', ru: 'Data Pipelines', pl: 'Potoki Danych' },
  service_pipelines_desc: { en: 'Robust ETL/ELT pipelines for your data workflows.', ru: 'Надежные ETL/ELT-пайплайны для ваших потоков данных.', pl: 'Solidne potoki ETL/ELT dla Twoich przepływów danych.' },
  service_integration_title: { en: 'API Integration', ru: 'API Интеграции', pl: 'Integracja API' },
  service_integration_desc: { en: 'Seamlessly connect your applications and services.', ru: 'Бесшовно соединяйте ваши приложения и сервисы.', pl: 'Bezproblemowo łącz swoje aplikacje i usługi.' },
  service_web3_title: { en: 'Web3 & DApps', ru: 'Web3 и DApps', pl: 'Web3 i DApps' },
  service_web3_desc: { en: 'Build decentralized applications on the blockchain.', ru: 'Создавайте децентрализованные приложения на блокчейне.', pl: 'Buduj zdecentralizowane aplikacje na blockchainie.' },

  // Service Page
  loading_content: { en: 'Generating service details...', ru: 'Генерируем детали услуги...', pl: 'Generowanie szczegółów usługi...' },
  error_content: { en: 'Failed to load content. Please try again later.', ru: 'Не удалось загрузить контент. Пожалуйста, попробуйте позже.', pl: 'Nie udało się załadować treści. Spróbuj ponownie później.' },
  key_features: { en: 'Key Features', ru: 'Ключевые особенности', pl: 'Kluczowe Funkcje' },
  real_world_use_case: { en: 'Real-World Use Case', ru: 'Пример использования', pl: 'Przykład Użycia w Rzeczywistym Świecie' },
  back_to_services: { en: 'Back to all services', ru: 'Назад ко всем услугам', pl: 'Wróć do wszystkich usług' },

  // Web Apps Service Details
  service_web_detailed: { en: 'Build high-performance, scalable web applications with our expert team. From responsive frontends to robust backends, we deliver solutions that grow with your business. Our applications are optimized for speed, security, and user experience, leveraging the latest technologies and best practices.', ru: 'Создавайте высокопроизводительные, масштабируемые веб-приложения с нашей экспертной командой. От адаптивных фронтэндов до надежных бэкэндов, мы предоставляем решения, которые растут вместе с вашим бизнесом. Наши приложения оптимизированы по скорости, безопасности и пользовательскому опыту.', pl: 'Buduj wysokowydajne, skalowalne aplikacje internetowe z naszym doświadczonym zespołem. Od responsywnych frontendów do niezawodnych backendów, dostarczamy rozwiązania, które rozwijają się wraz z Twoją firmą.' },
  service_web_features: { en: 'Modern React/Vue/Angular frameworks | Progressive Web Apps (PWA) | Real-time synchronization | Advanced SEO optimization | Mobile-first responsive design | Payment gateway integration | User authentication & security', ru: 'Современные фреймворки React/Vue/Angular | Progressive Web Apps (PWA) | Синхронизация в реальном времени | Продвинутая SEO-оптимизация | Адаптивный дизайн для мобильных | Интеграция платежных систем | Аутентификация и безопасность', pl: 'Nowoczesne frameworki React/Vue/Angular | Progressive Web Apps (PWA) | Synchronizacja w czasie rzeczywistym | Zaawansowana optymalizacja SEO | Responsywny design dla urządzeń mobilnych | Integracja bramek płatniczych | Uwierzytelnianie i bezpieczeństwo' },
  service_web_usecase: { en: 'A SaaS platform serving 50,000+ users globally, handling millions of transactions monthly. Our architecture ensures 99.9% uptime, sub-second response times, and seamless scaling during peak usage.', ru: 'SaaS платформа обслуживающая 50,000+ пользователей по всему миру, обрабатывающая миллионы транзакций ежемесячно. Наша архитектура обеспечивает 99.9% доступность, время отклика менее секунды и безшовное масштабирование при пиковых нагрузках.', pl: 'Platforma SaaS obsługująca 50 000+ użytkowników na całym świecie, obsługująca miliony transakcji miesięcznie. Nasza architektura zapewnia 99,9% czasu pracy, czasy odpowiedzi poniżej sekundy i bezproblemowe skalowanie podczas szczytowego użycia.' },

  // Cloud Servers Service Details
  service_server_detailed: { en: 'Enterprise-grade cloud servers with global distribution. Experience lightning-fast deployment, flexible resource allocation, and automatic scaling. Whether you need a single server or a complex multi-region setup, we handle the infrastructure so you focus on your application.', ru: 'Облачные серверы корпоративного уровня с глобальным распределением. Молниеносное развертывание, гибкое распределение ресурсов и автоматическое масштабирование. Все, от одного сервера до сложной мультирегиональной установки - мы управляем инфраструктурой.', pl: 'Serwery chmurowe klasy korporacyjnej z dystrybucją globalną. Błyskawiczne wdrożenie, elastyczne alokowanie zasobów i automatyczne skalowanie. Niezależnie od tego, czy potrzebujesz jednego serwera, czy złożonej konfiguracji wieloregionalnej, zajmujemy się infrastrukturą.' },
  service_server_features: { en: 'Auto-scaling load balancing | Advanced DDoS protection | 99.99% SLA uptime guarantee | Automated backups & disaster recovery | Advanced monitoring & alerts | SSH/API access | Root access | Multiple OS options', ru: 'Автоматическое масштабирование и балансировка нагрузки | Защита от DDoS | Гарантия доступности 99.99% SLA | Автоматические резервные копии и восстановление | Продвинутый мониторинг и оповещения | SSH/API доступ | Root доступ | Множество ОС', pl: 'Automatyczne skalowanie i balansowanie obciążenia | Zaawansowana ochrona przed DDoS | Gwarancja czasu pracy 99,99% SLA | Automatyczne kopie zapasowe i odzyskiwanie | Zaawansowany monitoring i alerty | Dostęp SSH/API | Dostęp root | Wiele opcji systemu operacyjnego' },
  service_server_usecase: { en: 'A fintech startup scaled from 1 server to 100+ servers across 5 continents, handling 1M+ daily transactions with zero downtime. Our auto-scaling infrastructure saved them $200K+ annually.', ru: 'Финтех стартап, масштабировавшийся от 1 сервера к 100+ серверам на 5 континентах, обрабатывающий 1М+ транзакций ежедневно без простоев. Наша инфраструктура с автомасштабированием сэкономила им $200K+ ежегодно.', pl: 'Startup fintech, który przeskalował się z 1 serwera na 100+ serwerów na 5 kontynentach, obsługując 1M+ transakcji dziennie bez przestojów. Nasza infrastruktura ze skalowaniem automatycznym zaoszczędziła im 200 tys. $ rocznie.' },

  // Data Science Service Details
  service_ds_detailed: { en: 'Transform your raw data into actionable intelligence. Our data science team uses cutting-edge ML models, statistical analysis, and AI algorithms to uncover patterns, predict trends, and drive business decisions. From exploratory analysis to production-ready models, we deliver complete solutions.', ru: 'Превратите ваши сырые данные в действенную информацию. Наша команда использует передовые ML-модели, статистический анализ и алгоритмы ИИ для выявления закономерностей, прогнозирования тенденций и принятия деловых решений. От исследовательского анализа до готовых к продакшену моделей - мы доставляем полные решения.', pl: 'Przekształć swoje surowe dane w praktyczną inteligencję biznesową. Nasz zespół data science wykorzystuje najnowocześniejsze modele ML, analizę statystyczną i algorytmy AI, aby odkrywać wzorce, przewidywać trendy i napędzać decyzje biznesowe.' },
  service_ds_features: { en: 'Machine Learning (regression, classification, clustering) | Deep Learning & Neural Networks | Natural Language Processing (NLP) | Computer Vision & Image Recognition | Time Series Forecasting | Anomaly Detection | Predictive Analytics', ru: 'Машинное обучение (регрессия, классификация, кластеризация) | Глубокое обучение и нейронные сети | Обработка естественного языка (NLP) | Компьютерное зрение и распознавание изображений | Прогнозирование временных рядов | Обнаружение аномалий | Прогнозная аналитика', pl: 'Machine Learning (regresja, klasyfikacja, klasteryzacja) | Głębokie uczenie i sieci neuronowe | Przetwarzanie języka naturalnego (NLP) | Wizja komputerowa i rozpoznawanie obrazów | Prognozowanie szeregów czasowych | Wykrywanie anomalii | Analityka predykcyjna' },
  service_ds_usecase: { en: 'Retail giant increased revenue by 23% by implementing our customer churn prediction model, enabling proactive retention campaigns. Processing 500M customer interactions monthly to deliver real-time insights.', ru: 'Гигант розничной торговли увеличил доход на 23% благодаря нашей модели прогнозирования оттока клиентов, что позволило проводить активные кампании удержания. Обработка 500М взаимодействий клиентов ежемесячно для выдачи информации в реальном времени.', pl: 'Gigant handlu detalicznego zwiększył przychody o 23% poprzez wdrożenie naszego modelu przewidywania rezygnacji klientów, umożliwiającego proaktywne kampanie retencji. Przetwarzanie 500M interakcji klientów miesięcznie w celu dostarczania informacji w czasie rzeczywistym.' },

  // Web Scraping Service Details
  service_scraping_detailed: { en: 'Extract, monitor, and process web data ethically and efficiently. Our web scraping solutions help you gather competitive intelligence, monitor market trends, and automate data collection at scale. Built with respect for web standards and target websites\' terms of service.', ru: 'Извлекайте, отслеживайте и обрабатывайте веб-данные этично и эффективно. Наши решения по веб-скрапингу помогают собирать конкурентную информацию, отслеживать рыночные тренды и автоматизировать сбор данных в масштабе. Построено с соблюдением веб-стандартов и условий использования целевых веб-сайтов.', pl: 'Wyodrębniaj, monitoruj i przetwarzaj dane internetowe etycznie i wydajnie. Nasze rozwiązania do web scrapingu pomagają zbierać informacje konkurencyjne, monitorować trendy rynkowe i automatyzować zbieranie danych na dużą skalę.' },
  service_scraping_features: { en: 'High-performance distributed scraping | JavaScript rendering support | Proxy rotation & IP management | Data validation & cleaning | Scheduling & automation | Email alerts & notifications | Rate limiting compliance', ru: 'Высокопроизводительный распределенный скрапинг | Поддержка рендеринга JavaScript | Ротация прокси и управление IP | Валидация и очистка данных | Планирование и автоматизация | Оповещения по электронной почте | Соответствие ограничениям скорости', pl: 'Wysokowydajny rozproszony scraping | Obsługa renderowania JavaScript | Rotacja proxy i zarządzanie IP | Walidacja i czyszczenie danych | Planowanie i automatyzacja | Alerty e-mail | Zgodność z ograniczeniami szybkości' },
  service_scraping_usecase: { en: 'Price comparison platform scrapes 100K+ product listings daily across 50+ retailers, enabling customers to find the best deals. Processing data from dynamic JavaScript-heavy websites with 99.8% accuracy.', ru: 'Платформа сравнения цен собирает 100K+ объявлений товаров ежедневно на 50+ розничных сайтах, позволяя клиентам найти лучшие предложения. Обработка данных с динамических JavaScript-интенсивных веб-сайтов с точностью 99.8%.', pl: 'Platforma porównania cen zbiera 100K+ aukcji produktów dziennie na 50+ sprzedawcach detalicznych, umożliwiając klientom znalezienie najlepszych ofert. Przetwarzanie danych z dynamicznych stron internetowych opartych na JavaScript z dokładnością 99,8%.' },

  // Data Pipelines Service Details
  service_pipelines_detailed: { en: 'Build robust, scalable ETL/ELT pipelines that transform data from multiple sources into valuable insights. Our solutions handle data validation, transformation, enrichment, and loading with minimal latency. From batch processing to real-time streaming, we design pipelines that work seamlessly at any scale.', ru: 'Создавайте надежные, масштабируемые ETL/ELT пайплайны, которые преобразуют данные из множества источников в ценную информацию. Наши решения обрабатывают валидацию, преобразование, обогащение и загрузку данных с минимальной задержкой. От пакетной обработки к потоковой обработке в реальном времени - мы проектируем пайплайны, работающие безшовно в любом масштабе.', pl: 'Buduj solidne, skalowalne potoki ETL/ELT, które transformują dane z wielu źródeł w cenne informacje. Nasze rozwiązania obsługują walidację danych, transformację, wzbogacanie i ładowanie z minimalnym opóźnieniem.' },
  service_pipelines_features: { en: 'Apache Airflow & Kafka integration | Real-time streaming (Flink, Spark) | Data quality monitoring | Schema validation | Error handling & retries | Cost optimization | Multi-cloud support', ru: 'Интеграция Apache Airflow и Kafka | Потоковая обработка в реальном времени (Flink, Spark) | Мониторинг качества данных | Валидация схемы | Обработка ошибок и повторы | Оптимизация затрат | Поддержка мультиоблака', pl: 'Integracja Apache Airflow i Kafka | Streaming w czasie rzeczywistym (Flink, Spark) | Monitoring jakości danych | Walidacja schematu | Obsługa błędów i ponowienia | Optymalizacja kosztów | Obsługa wielochmury' },
  service_pipelines_usecase: { en: 'E-commerce company processes 2TB+ of daily data across 10 systems. Our ELT pipeline delivers analytics to decision makers in <5 minutes instead of overnight, increasing revenue by 18%.', ru: 'Компания электронной коммерции обрабатывает 2TB+ данных ежедневно на 10 системах. Наш ELT пайплайн доставляет аналитику лицам, принимающим решения, за <5 минут вместо ночи, увеличивая доход на 18%.', pl: 'Firma e-commerce przetwarza 2TB+ danych dziennie w 10 systemach. Nasz potok ELT dostarcza analitykę decydentom w <5 minut zamiast przesuwać do nocy, zwiększając przychód o 18%.' },

  // API Integration Service Details
  service_integration_detailed: { en: 'Connect your applications seamlessly with third-party services, APIs, and custom integrations. Our team specializes in building scalable integrations that ensure data consistency, security, and reliability. From payment gateways to CRM systems, we handle the complexity so you can focus on core features.', ru: 'Бесшовно подключайте ваши приложения к сторонним сервисам, API и пользовательским интеграциям. Наша команда специализируется на создании масштабируемых интеграций, обеспечивающих согласованность, безопасность и надежность данных. От платежных шлюзов до систем CRM - мы справляемся со сложностью.', pl: 'Bezproblemowo połącz swoje aplikacje z usługami stron trzecich, interfejsami API i niestandardowymi integracjami. Nasz zespół specjalizuje się w budowaniu skalowalnych integracji, które zapewniają spójność, bezpieczeństwo i niezawodność danych.' },
  service_integration_features: { en: 'REST & GraphQL APIs | OAuth/JWT authentication | Webhook management | Rate limiting & throttling | Error logging & monitoring | Batch processing | Multi-tenant support', ru: 'REST и GraphQL API | OAuth/JWT аутентификация | Управление вебхуками | Ограничение скорости и дроссинг | Логирование и мониторинг ошибок | Пакетная обработка | Поддержка мультитенанта', pl: 'Interfejsy API REST i GraphQL | Uwierzytelnianie OAuth/JWT | Zarządzanie webhookami | Ograniczanie szybkości i przepustowości | Logowanie błędów i monitoring | Przetwarzanie wsadowe | Obsługa multi-tenant' },
  service_integration_usecase: { en: 'Integrated 15+ payment and shipping APIs into a unified platform, reducing transaction processing time by 40% and support tickets by 60%. Handles 500K+ API calls daily with 99.95% success rate.', ru: 'Интегрировано 15+ платежных и доставочных API в единую платформу, сокращая время обработки транзакции на 40% и тикеты поддержки на 60%. Обрабатывает 500K+ вызовов API ежедневно с успешностью 99.95%.', pl: 'Zintegrowano 15+ interfejsów API płatności i wysyłki w ujednoliconą platformę, zmniejszając czas przetwarzania transakcji o 40% i bilety obsługi o 60%. Obsługuje 500K+ połączeń API dziennie z wskaźnikiem powodzenia 99,95%.' },

  // Web3 & DApps Service Details
  service_web3_detailed: { en: 'Build the future of decentralized applications. Our blockchain expertise spans Ethereum, Polygon, Solana, and more. We create smart contracts, DeFi protocols, NFT platforms, and Web3 infrastructure. From concept to mainnet deployment, we guide you through blockchain development with security and scalability in mind.', ru: 'Стройте будущее децентрализованных приложений. Наш опыт блокчейна охватывает Ethereum, Polygon, Solana и многое другое. Мы создаем смарт-контракты, DeFi протоколы, NFT платформы и инфраструктуру Web3. От концепции к развертыванию на основной сети - мы помогаем вам разработать блокчейн-приложение с соблюдением безопасности и масштабируемости.', pl: 'Buduj przyszłość zdecentralizowanych aplikacji. Nasza wiedza blockchain obejmuje Ethereum, Polygon, Solanę i wiele więcej. Tworzymy inteligentne kontrakty, protokoły DeFi, platformy NFT i infrastrukturę Web3.' },
  service_web3_features: { en: 'Solidity & smart contract development | DeFi protocol design | NFT minting & marketplaces | Wallet integration | Cross-chain bridges | Gas optimization | Security audits', ru: 'Разработка Solidity и смарт-контрактов | Проектирование DeFi протоколов | Чеканка NFT и маркетплейсы | Интеграция кошельков | Межцепочковые мосты | Оптимизация газа | Аудит безопасности', pl: 'Programowanie Solidity i inteligentne kontrakty | Projektowanie protokołów DeFi | Mintowanie NFT i rynki | Integracja portfela | Mosty cross-chain | Optymalizacja gazu | Audyty bezpieczeństwa' },
  service_web3_usecase: { en: 'Launched a DeFi protocol managing $500M+ TVL with 100K+ daily active users. Smart contracts audited by tier-1 firms, handling 1M+ transactions daily with zero security incidents since launch.', ru: 'Запущен DeFi протокол с управлением $500M+ TVL и 100K+ ежедневно активных пользователей. Смарт-контракты проверены ведущими фирмами, обрабатывают 1M+ транзакций ежедневно без инцидентов безопасности с момента запуска.', pl: 'Uruchomiony protokół DeFi zarządzający 500M+ TVL z 100K+ codziennymi aktywnymi użytkownikami. Inteligentne kontrakty zbadane przez firmy najwyższego poziomu, obsługujące 1M+ transakcji dziennie bez incydentów bezpieczeństwa od momentu uruchomienia.' },

  // Contacts Page
  contacts_title: { en: 'Contact Us', ru: 'Свяжитесь с нами', pl: 'Skontaktuj się z nami' },
  contacts_description: { en: 'If you have any questions, feel free to reach out to us.', ru: 'Если у вас есть вопросы, не стесняйтесь обращаться к нам.', pl: 'Jeśli masz jakieś pytania, skontaktuj się z nami.' },
  email_label: { en: 'Email', ru: 'Электронная почта', pl: 'E-mail' },
};
